// <auto-generated />
using System;
using Bloqqer.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bloqqer.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240723223429_MigrationV1")]
    partial class MigrationV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Bloqqer.ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff892bdc-1b25-4341-bad3-121dcc14c26f",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 671, DateTimeKind.Utc).AddTicks(4951),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "admin@iyyel.io",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "",
                            LockoutEnabled = false,
                            MiddleName = "",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            NormalizedEmail = "ADMIN@IYYEL.IO",
                            NormalizedUserName = "ADMIN@IYYEL.IO",
                            PasswordHash = "AQAAAAIAAYagAAAAEDvbbwu1qXomSE/vAeBkwKlzkPI3xmDXkn4pc/YtmdnlGIOChfVr2gkz3jXYcBXMew==",
                            PhoneNumber = "21212121",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "admin",
                            TwoFactorEnabled = false,
                            UserName = "admin@iyyel.io"
                        },
                        new
                        {
                            Id = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51c58c06-1cc6-40c2-99ef-20012d6585b4",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8876),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "mail@iyyel.io",
                            EmailConfirmed = true,
                            FirstName = "Daniel",
                            LastName = "",
                            LockoutEnabled = false,
                            MiddleName = "",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            NormalizedEmail = "MAIL@IYYEL.IO",
                            NormalizedUserName = "MAIL@IYYEL.IO",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFyrnZI2DCZ+HjHR1Oxr7Lpz67EqVX4cg3D7p/DZX2KGx/xBEcv6Xl7qSe8wuLwLg==",
                            PhoneNumber = "20202020",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "user",
                            TwoFactorEnabled = false,
                            UserName = "mail@iyyel.io"
                        },
                        new
                        {
                            Id = new Guid("5734941b-03c9-4416-9451-b32d2a0e4cc0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6b3cee5-867c-43ad-8cb0-0d1cb9463f0b",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(232),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "james@butler.xyz",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastName = "Butler",
                            LockoutEnabled = false,
                            MiddleName = "Henrich",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            NormalizedEmail = "JAMES@BUTLER.XYZ",
                            NormalizedUserName = "JAMES@BUTLER.XYZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEJW1y2zulDOSuBXF/77Av4QFhQm5YHFdG4y7N3pKzWjVFCg+9VejejXFw8OdB7F/aA==",
                            PhoneNumber = "23232323",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "james",
                            TwoFactorEnabled = false,
                            UserName = "james@butler.xyz"
                        });
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Bloq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Published")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Bloqqer.Bloqs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("295efc76-56d6-4839-ada4-25924f912aa0"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8584),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Admin Seed Bloq Description 1/2",
                            IsPrivate = false,
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8582),
                            Title = "Admin Seed Bloq Title 1/2"
                        },
                        new
                        {
                            Id = new Guid("f8d31b28-1c9a-43c0-aebd-19236af4422f"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8591),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Admin Seed Bloq Description 2/2",
                            IsPrivate = true,
                            IsPublished = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Admin Seed Bloq Title 2/2"
                        },
                        new
                        {
                            Id = new Guid("dc5b12fd-f5a3-4a04-a6e0-c4cd552cd6b5"),
                            AuthorId = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(33),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Daniel Seed Bloq Description",
                            IsPrivate = false,
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(31),
                            Title = "Daniel Seed Bloq Title"
                        });
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Published")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Bloqqer.Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1af0038f-73a2-4fbb-867f-75a90cf33536"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            Content = "Admin Seed Bloq Post 1 Comment 1/2",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8607),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("0cb3379f-6bea-424d-ba0f-a44f4fa6a11a"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8606)
                        },
                        new
                        {
                            Id = new Guid("180daba0-d465-40d0-bb01-68e0ac40b86c"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            Content = "Admin Seed Bloq Post 1 Comment 2/2",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8609),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("0cb3379f-6bea-424d-ba0f-a44f4fa6a11a")
                        },
                        new
                        {
                            Id = new Guid("3e8f006d-04c7-4d2b-97a2-108de9b39b3a"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            Content = "Admin Seed Bloq Post 2 Comment 1/2",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8610),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("efab75ca-f1ac-4211-8076-e344b9c98025"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8610)
                        },
                        new
                        {
                            Id = new Guid("fcc41c42-f406-4b28-9b4f-c7e02ccb6380"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            Content = "Admin Seed Bloq Post 2 Comment 2/2",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8611),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("efab75ca-f1ac-4211-8076-e344b9c98025")
                        },
                        new
                        {
                            Id = new Guid("d1cd67d2-67e5-4c6f-aabb-cb4056dd5064"),
                            AuthorId = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            Content = "Daniel Seed Bloq Post 1 Comment 1/3",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(47),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("0afda5fc-0a56-45b6-a983-3018048c204a"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(47)
                        },
                        new
                        {
                            Id = new Guid("49304138-ec9e-495e-8774-d4b2b64781ce"),
                            AuthorId = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            Content = "Daniel Seed Bloq Post 1 Comment 2/3",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(49),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("0afda5fc-0a56-45b6-a983-3018048c204a"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(49)
                        },
                        new
                        {
                            Id = new Guid("679dee46-f2f2-4859-bedc-7d542eae5089"),
                            AuthorId = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            Content = "Daniel Seed Bloq Post 1 Comment 3/3",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(51),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostId = new Guid("0afda5fc-0a56-45b6-a983-3018048c204a"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(50)
                        });
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FollowedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FollowedId");

                    b.HasIndex("FollowerId");

                    b.ToTable("Bloqqer.Follows", (string)null);
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BloqId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Published")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BloqId");

                    b.ToTable("Bloqqer.Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cb3379f-6bea-424d-ba0f-a44f4fa6a11a"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            BloqId = new Guid("295efc76-56d6-4839-ada4-25924f912aa0"),
                            Content = "Admin Seed Bloq Post 1/2 Content",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8599),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Admin Seed Bloq Post 1/2 Description",
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8598),
                            Title = "Admin Seed Bloq Post 1/2"
                        },
                        new
                        {
                            Id = new Guid("efab75ca-f1ac-4211-8076-e344b9c98025"),
                            AuthorId = new Guid("c108f0d4-7f9f-49eb-8a18-9f9bd81e1765"),
                            BloqId = new Guid("295efc76-56d6-4839-ada4-25924f912aa0"),
                            Content = "Admin Seed Bloq Post 2/2 Content",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 709, DateTimeKind.Utc).AddTicks(8602),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Admin Seed Bloq Post 2/2 Description",
                            IsPublished = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Admin Seed Bloq Post 2/2"
                        },
                        new
                        {
                            Id = new Guid("0afda5fc-0a56-45b6-a983-3018048c204a"),
                            AuthorId = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            BloqId = new Guid("dc5b12fd-f5a3-4a04-a6e0-c4cd552cd6b5"),
                            Content = "Daniel Seed Bloq Post 1/2 Content",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(40),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Daniel Seed Bloq Post 1/2 Description",
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(40),
                            Title = "Daniel Seed Bloq Post 1/2"
                        },
                        new
                        {
                            Id = new Guid("f298d1f6-9ae6-477c-af37-173f959cdd1c"),
                            AuthorId = new Guid("de05b775-a344-497f-a091-643d267ff25d"),
                            BloqId = new Guid("dc5b12fd-f5a3-4a04-a6e0-c4cd552cd6b5"),
                            Content = "Daniel Seed Bloq Post 2/2 Content",
                            CreatedBy = new Guid("2afb7b32-9305-4c43-90d3-78412603e4ff"),
                            CreatedOn = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(43),
                            DeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Daniel Seed Bloq Post 2/2 Description",
                            IsPublished = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Published = new DateTime(2024, 7, 23, 22, 34, 28, 747, DateTimeKind.Utc).AddTicks(43),
                            Title = "Daniel Seed Bloq Post 2/2"
                        });
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BloqId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReactorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BloqId");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReactorId");

                    b.ToTable("Bloqqer.Reactions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Bloq", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", "Author")
                        .WithMany("Bloqs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Comment", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloqqer.Infrastructure.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Follow", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", "Followed")
                        .WithMany("Following")
                        .HasForeignKey("FollowedId");

                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Post", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloqqer.Infrastructure.Models.Bloq", "Bloq")
                        .WithMany("Posts")
                        .HasForeignKey("BloqId");

                    b.Navigation("Author");

                    b.Navigation("Bloq");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Reaction", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.Bloq", "Bloq")
                        .WithMany("Reactions")
                        .HasForeignKey("BloqId");

                    b.HasOne("Bloqqer.Infrastructure.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId");

                    b.HasOne("Bloqqer.Infrastructure.Models.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId");

                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", "Reactor")
                        .WithMany("Reactions")
                        .HasForeignKey("ReactorId");

                    b.Navigation("Bloq");

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("Reactor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Bloqqer.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bloqs");

                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Bloq", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Bloqqer.Infrastructure.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
